# Dockerfile
FROM php:8.3-cli

# Essenciais apenas
RUN apt-get update && apt-get install -y \
    git unzip libpq-dev \
    && docker-php-ext-install pdo_pgsql bcmath \
    && apt-get clean

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app
COPY . .

# Instalar dependências (sem dev)
RUN composer install --no-dev --optimize-autoloader

# Iniciar
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]