services:
  - type: web
    name: meu-app-laravel
    runtime: docker
    repo: https://github.com/seu-usuario/seu-repo
    branch: main
    dockerCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
